# Generated by Django 2.0.8 on 2019-03-20 15:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('hall_type', models.CharField(choices=[('Small', '50 People'), ('Medium', '100 People'), ('Large', 'ABove 100 People')], default=None, max_length=264)),
                ('vacant', models.BooleanField(default=False)),
                ('particulars', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='media/HallPics/')),
                ('booked_on', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hall_Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('Morning', '9am-11:15'), ('Break', '1:15'), ('Evening', '3pm-5pm')], default=None, max_length=264)),
                ('requested_on', models.DateTimeField(default=datetime.datetime(2019, 3, 20, 15, 45, 4, 692298, tzinfo=utc))),
                ('booking_required', models.DateTimeField(default=None, null=True)),
                ('approved_bookings', models.BooleanField(default=False)),
                ('hall', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='Halls.Hall')),
                ('requested_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
