# Generated by Django 2.0.8 on 2019-03-20 15:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Halls', '0002_auto_20190320_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall_booking',
            name='requested_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 20, 15, 55, 13, 616210, tzinfo=utc)),
        ),
    ]
