# Generated by Django 2.0.8 on 2019-03-20 16:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Halls', '0004_auto_20190320_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall_booking',
            name='booking_required',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='hall_booking',
            name='requested_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 20, 16, 11, 29, 426518, tzinfo=utc)),
        ),
    ]
